version: '3.1'
services: 
  mysql:
    image: mysql
    platform: linux/amd64
    container_name: msql
    command: mysqld --user=root
    ports:
      - 3333:3306
    environment:
      - MYSQL_DATABASE=go-ywd-test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
    links: 
      - mysql

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  go-ywd-test:
    image: watcharis/watcharis:go-ywd-test-v0.0.9
    container_name: go-ywd-test
    restart: always
    ports:
      - 3213:1323
    environment: 
      - DBUSER=admin
      - DBPASSWORD=password
      - DBHOST=172.17.0.1
      - DBPORT=3333
      - DBNAME=go-ywd-test
      - DBURL=admin:password@tcp(172.17.0.1:3333)/go-ywd-test?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_URL=redis:6379
      - FLASK_URL_CONONE=http://172.17.0.1:4567/nodepromise1
      - FLASK_URL_CONTWO=http://172.17.0.1:4567/nodepromise2
      - FLASK_URL_CONTHREE=http://172.17.0.1:4567/nodepromise3
      - FLASK_URL_CONFOUR=http://172.17.0.1:4567/nodepromise4
    links: 
      - mysql
      - redis
    depends_on: 
      - mysql
      - redis
      - adminer
    # network_mode: bridge
