version: '3.1'
services: 
  mysql:
    image: mysql
    container_name: msql
    command: mysqld --user=root
    ports:
      - 3333:3306
    environment:
      - MYSQL_DATABASE=go-ywd-test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
    links: 
      - mysql
  # redis:
  #   image: "redis:6.2.4-alpine"
  #   container_name: redis-go-ywd
  #   ports:
  #     - 6379:6379
  #   restart: always
  
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
        - ALLOW_EMPTY_PASSWORD=yes